name: "Pylint using flake 8"
description: "Pylint using flake 8"

runs:
  using: "composite"
  steps:
    - name: Lint with flake8
      shell: bash
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics